import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'

function ScanCode() {
  const navigate = useNavigate()
  const [code, setCode] = useState('')
  const [error, setError] = useState('')
  const [isScanning, setIsScanning] = useState(false)
  const [scannerSupported] = useState(() => 'BarcodeDetector' in window && !!navigator.mediaDevices?.getUserMedia)
  const videoRef = useRef(null)
  const streamRef = useRef(null)
  const scanTimerRef = useRef(null)

  const stopScanner = () => {
    if (scanTimerRef.current) {
      window.clearInterval(scanTimerRef.current)
      scanTimerRef.current = null
    }
    streamRef.current?.getTracks().forEach((track) => track.stop())
    streamRef.current = null
    setIsScanning(false)
  }

  useEffect(() => () => stopScanner(), [])

  const getQueueId = (value) => {
    const scannedValue = value.trim()
    const rawQueueId = scannedValue.match(/^LW-[A-Z0-9]+$/i)
    if (rawQueueId) return rawQueueId[0].toUpperCase()

    try {
      const url = new URL(scannedValue)
      const match = url.pathname.match(/^\/join\/([^/?#]+)$/i)
      return match ? decodeURIComponent(match[1]).toUpperCase() : ''
    } catch {
      return ''
    }
  }

  const handleScanResult = (value) => {
    const queueId = getQueueId(value)
    if (!queueId) {
      setError('This QR code is not a LineWise queue code.')
      return
    }
    stopScanner()
    navigate(`/join/${queueId}`)
  }

  const startScanner = async () => {
    setError('')
    if (!scannerSupported) {
      setError('Camera QR scanning is not supported by this browser. Please use Chrome on your phone or enter the Queue ID.')
      return
    }

    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: { ideal: 'environment' } },
        audio: false,
      })
      streamRef.current = stream
      setIsScanning(true)

      // Wait for React to attach the video element before starting detection.
      window.setTimeout(async () => {
        if (!videoRef.current) return
        videoRef.current.srcObject = stream
        await videoRef.current.play()
        const detector = new window.BarcodeDetector({ formats: ['qr_code'] })
        scanTimerRef.current = window.setInterval(async () => {
          try {
            const codes = await detector.detect(videoRef.current)
            if (codes.length) handleScanResult(codes[0].rawValue)
          } catch {
            // A frame can be unavailable while the camera initializes; keep scanning.
          }
        }, 400)
      }, 0)
    } catch {
      setError('Camera access was denied or unavailable. Allow camera permission, then try again.')
      stopScanner()
    }
  }

  const handleManualSubmit = (e) => {
    e.preventDefault()
    const cleanCode = code.trim().toUpperCase()
    if (!cleanCode) {
      setError('Please enter a Queue ID')
      return
    }
    // Navigate to Join Queue page
    navigate(`/join/${cleanCode}`)
  }

  return (
    <section className="bg-gradient-to-b from-blue-50 to-white dark:from-slate-900 dark:to-slate-950 min-h-screen px-6 py-16 transition-colors duration-200">
      <div className="mx-auto max-w-md text-center">
        <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
          Scan or Enter Queue Code
        </h1>
        <p className="mt-2 text-gray-600 dark:text-slate-400">
          Scan the counter QR code with your camera, or enter the Queue ID manually.
        </p>

        <div className="mt-8 bg-white dark:bg-slate-900 p-6 rounded-2xl shadow-sm border border-blue-100 dark:border-slate-800 space-y-4">
          {isScanning ? (
            <>
              <video ref={videoRef} muted playsInline className="w-full rounded-xl bg-black aspect-square object-cover" />
              <button type="button" onClick={stopScanner} className="w-full py-3 border border-gray-300 dark:border-slate-700 rounded-xl font-semibold text-gray-700 dark:text-slate-200">
                Stop Camera
              </button>
            </>
          ) : (
            <button type="button" onClick={startScanner} className="w-full py-4 bg-blue-600 text-white font-semibold rounded-xl shadow-md hover:bg-blue-700 transition">
              Scan Queue QR Code
            </button>
          )}
          <p className="text-xs text-gray-500 dark:text-slate-400">Allow camera access when prompted. The QR code must be generated by LineWise.</p>
        </div>

        <form
          onSubmit={handleManualSubmit}
          className="mt-8 bg-white dark:bg-slate-900 p-8 rounded-2xl shadow-sm border border-blue-100 dark:border-slate-800 space-y-4 text-left"
        >
          {error && (
            <div className="p-3 bg-red-50 dark:bg-red-950/60 text-red-700 dark:text-red-300 border border-red-200 dark:border-red-900 text-xs font-semibold rounded-xl">
              {error}
            </div>
          )}

          <div>
            <label className="block text-xs font-bold text-gray-700 dark:text-slate-300 uppercase mb-2">
              Queue ID / Code
            </label>
            <input
              type="text"
              value={code}
              onChange={(e) => setCode(e.target.value)}
              placeholder="e.g. LW-7A8B9C"
              className="w-full px-4 py-3 font-mono text-lg rounded-xl border border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 uppercase"
            />
          </div>

          <button
            type="submit"
            className="w-full py-4 bg-blue-600 text-white font-semibold rounded-xl shadow-md hover:bg-blue-700 transition"
          >
            Find Queue & Join Line
          </button>
        </form>
      </div>
    </section>
  )
}

export default ScanCode
